/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PharmacyRouteImport } from './routes/pharmacy'
import { Route as PatientsRouteImport } from './routes/patients'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BurnoutRouteImport } from './routes/burnout'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as AiAssistRouteImport } from './routes/ai-assist'
import { Route as IndexRouteImport } from './routes/index'

const PharmacyRoute = PharmacyRouteImport.update({
  id: '/pharmacy',
  path: '/pharmacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsRoute = PatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BurnoutRoute = BurnoutRouteImport.update({
  id: '/burnout',
  path: '/burnout',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAssistRoute = AiAssistRouteImport.update({
  id: '/ai-assist',
  path: '/ai-assist',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-assist': typeof AiAssistRoute
  '/appointments': typeof AppointmentsRoute
  '/burnout': typeof BurnoutRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/patients': typeof PatientsRoute
  '/pharmacy': typeof PharmacyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-assist': typeof AiAssistRoute
  '/appointments': typeof AppointmentsRoute
  '/burnout': typeof BurnoutRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/patients': typeof PatientsRoute
  '/pharmacy': typeof PharmacyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-assist': typeof AiAssistRoute
  '/appointments': typeof AppointmentsRoute
  '/burnout': typeof BurnoutRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/patients': typeof PatientsRoute
  '/pharmacy': typeof PharmacyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-assist'
    | '/appointments'
    | '/burnout'
    | '/dashboard'
    | '/login'
    | '/patients'
    | '/pharmacy'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-assist'
    | '/appointments'
    | '/burnout'
    | '/dashboard'
    | '/login'
    | '/patients'
    | '/pharmacy'
  id:
    | '__root__'
    | '/'
    | '/ai-assist'
    | '/appointments'
    | '/burnout'
    | '/dashboard'
    | '/login'
    | '/patients'
    | '/pharmacy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiAssistRoute: typeof AiAssistRoute
  AppointmentsRoute: typeof AppointmentsRoute
  BurnoutRoute: typeof BurnoutRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  PatientsRoute: typeof PatientsRoute
  PharmacyRoute: typeof PharmacyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pharmacy': {
      id: '/pharmacy'
      path: '/pharmacy'
      fullPath: '/pharmacy'
      preLoaderRoute: typeof PharmacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients': {
      id: '/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/burnout': {
      id: '/burnout'
      path: '/burnout'
      fullPath: '/burnout'
      preLoaderRoute: typeof BurnoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-assist': {
      id: '/ai-assist'
      path: '/ai-assist'
      fullPath: '/ai-assist'
      preLoaderRoute: typeof AiAssistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiAssistRoute: AiAssistRoute,
  AppointmentsRoute: AppointmentsRoute,
  BurnoutRoute: BurnoutRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  PatientsRoute: PatientsRoute,
  PharmacyRoute: PharmacyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
